FROM mcr.microsoft.com/azure-functions/node:4-node16-core-tools
ENV AzureWebJobsScriptRoot=/home/site/wwwroot \
    AzureFunctionsJobHost__Logging__Console__IsEnabled=true
WORKDIR /home/site/wwwroot
COPY package*.json ./
RUN npm install
COPY functions ./
RUN npm run functions:build
CMD [ "npm", "run", "functions:start" ]
