name: Build and Deploy App Service

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/build-deploy-appservice.yaml
      - react**

env:
  APP_SERVICE_NAME: qatranslator-je-appservice
  GHCR_IMAGE_NAME: react
  GHCR_REPOSITORY_NAME: qatranslator

jobs:
  build-ghcr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Login Azure as Contributor
        uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.AZURE_AD_SP_CONTRIBUTOR_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_AD_SP_CONTRIBUTOR_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'
          enable-AzPSSession: true

      - name: Get API Management Subscription Key
        id: get_api_management_subscription_key
        uses: azure/powershell@v1
        with:
          inlineScript: |
            $apimContext = New-AzApiManagementContext `
              -ResourceGroupName "${{ env.RESOURCE_GROUP }}" `
              -ServiceName "${{ env.APIM_NAME }}"
            $apimFunctionsSubscriptionKey = Get-AzApiManagementSubscriptionKey `
              -Context $apimContext `
              -SubscriptionId "subscriptions-functions"
            $apimSubscriptionKey = $apimFunctionsSubscriptionKey.PrimaryKey
            Write-Output "::add-mask::${apimSubscriptionKey}"
            Write-Output "::set-output name=apim_subscription_key::${apimSubscriptionKey}"
          azPSVersion: latest

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Build and Docker Push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: react/Dockerfile
          push: true
          tags: ghcr.io/${{ github.actor }}/${{ env.GHCR_REPOSITORY_NAME }}/${{ env.GHCR_IMAGE_NAME }}:${{ github.sha	}}
          secrets: |
            REACT_APP_API_MANAGEMENT_SUBSCRIPTION_KEY=${{ steps.get_api_management_subscription_key.outputs.apim_subscription_key }}
            REACT_APP_AZURE_AD_SP_MSAL_CLIENT_ID=${{ secrets.AZURE_AD_SP_MSAL_CLIENT_ID }}
            REACT_APP_AZURE_TENANT_ID=${{ secrets.AZURE_TENANT_ID }}
            REACT_APP_DEEPL_AUTH_KEY=${{ secrets.DEEPL_AUTH_KEY }}

  deploy-appservice:
    runs-on: ubuntu-latest
    needs: build-ghcr
    steps:
      - name: Login Azure as Contributor
        uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.AZURE_AD_SP_CONTRIBUTOR_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_AD_SP_CONTRIBUTOR_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'

      - name: Deploy App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.APP_SERVICE_NAME }}
          images: ghcr.io/${{ github.actor }}/${{ env.GHCR_REPOSITORY_NAME }}/${{ env.GHCR_IMAGE_NAME }}:${{ github.sha	}}
