name: Build and Deploy App Service

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/build-deploy-appservice.yaml
      - .github/workflows/reusable-build-appservice.yaml
      - .github/workflows/reusable-deploy-appservice.yaml
      - react**

jobs:
  use-build-appservice-workflow:
    uses: ./.github/workflows/reusable-build-appservice.yaml
    secrets:
      AZURE_AD_SP_CONTRIBUTOR_CLIENT_ID: ${{ secrets.AZURE_AD_SP_CONTRIBUTOR_CLIENT_ID }}
      AZURE_AD_SP_CONTRIBUTOR_CLIENT_SECRET: ${{ secrets.AZURE_AD_SP_CONTRIBUTOR_CLIENT_SECRET }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

  use-deploy-appservice-workflow:
    needs: use-build-appservice-workflow
    uses: ./.github/workflows/reusable-deploy-appservice.yaml
    secrets:
      AZURE_AD_SP_CONTRIBUTOR_CLIENT_ID: ${{ secrets.AZURE_AD_SP_CONTRIBUTOR_CLIENT_ID }}
      AZURE_AD_SP_CONTRIBUTOR_CLIENT_SECRET: ${{ secrets.AZURE_AD_SP_CONTRIBUTOR_CLIENT_SECRET }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
