name: Build and Deploy React Server

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/build-deploy-react.yaml
      - react**

env:
  ACI_NAME: qatranslator-je-aci
  GHCR_IMAGE_NAME: react
  GHCR_REPOSITORY_NAME: qatranslator

jobs:
  build-ghcr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: react/Dockerfile
          push: true
          tags: ghcr.io/${{ github.actor }}/${{ env.GHCR_REPOSITORY_NAME }}/${{ env.GHCR_IMAGE_NAME }}:${{ github.sha	}}

  # deploy-aci:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Login Azure as Contributor
  #       uses: azure/login@v1
  #       with:
  #         creds: '{"clientId":"${{ secrets.AZURE_AD_SP_CONTRIBUTOR_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_AD_SP_CONTRIBUTOR_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'
