name: Deploy API Management

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/deploy-apim.yaml
      - apim**

jobs:
  deploy-apim:
    uses: ./.github/workflows/reusable-deploy-apim.yaml
