name: Regenerate Keys

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

env:
  COGNITIVE_NAME: qatranslator-je-cognitive
  # COSMOSDB_NAME: qatranslator-je-cosmosdb
  # FUNCTIONS_NAME: qatranslator-je-func
  RESOURCE_GROUP: qatranslator-je
  # STORAGE_ACCOUNT_NAME: qatranslatorjesa
  VAULT_NAME: qatranslator-je-vault

jobs:
  cognitive:
    runs-on: ubuntu-latest
    steps:
      - name: Login Azure as Contributor
        uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ vars.AZURE_AD_SP_CONTRIBUTOR_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_AD_SP_CONTRIBUTOR_CLIENT_SECRET }}","subscriptionId":"${{ vars.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ vars.AZURE_TENANT_ID }}"}'

      - name: Regenerate Cognitive Key2 and Set into Vault
        run: |
          regeneratedKey2=$( \
            az cognitiveservices account keys regenerate \
              -g ${{ env.RESOURCE_GROUP }} \
              -n ${{ env.COGNITIVE_NAME }} \
              --key-name key2 \
              --query key2 \
              -o tsv \
          )
          az keyvault secret set \
            --vault-name ${{ env.VAULT_NAME }} \
            -n cognitive-key \
            --value ${regeneratedKey2} \
            --query attributes.created \
            -o tsv

      - name: Regenerate Cognitive Key1 and Set into Vault
        run: |
          regeneratedKey1=$( \
            az cognitiveservices account keys regenerate \
              -g ${{ env.RESOURCE_GROUP }} \
              -n ${{ env.COGNITIVE_NAME }} \
              --key-name key1 \
              --query key1 \
              -o tsv \
          )
          az keyvault secret set \
            --vault-name ${{ env.VAULT_NAME }} \
            -n cognitive-key \
            --value ${regeneratedKey1} \
            --query attributes.created \
            -o tsv
