name: Deploy API Management (Reusable Workflow)

on:
  workflow_call:

env:
  APIM_APIS_NAME: apis-functions
  APIM_NAME: qatranslator-je-apim
  RESOURCE_GROUP: qatranslator-je

jobs:
  deploy-apim:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Login Azure as Contributor
        uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.AZURE_AD_SP_CONTRIBUTOR_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_AD_SP_CONTRIBUTOR_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'

      - name: Import Swagger into API Management
        run: |
          az apim api import \
            -g ${{ env.RESOURCE_GROUP }} \
            -n ${{ env.APIM_NAME }} \
            --path "api" \
            --specification-format OpenApi \
            --api-id ${{ env.APIM_APIS_NAME }} \
            --specification-path ./apim/swagger.yaml
