name: Build App Service (Reusable Workflow)

on:
  workflow_call:
    inputs:
      APIM_NAME:
        default: qatranslator-je-apim
        required: false
        type: string
      APIM_SUBSCRIPTION_NAME:
        default: subscriptions-functions
        required: false
        type: string
      COGNITIVE_NAME:
        default: qatranslator-je-cognitive
        required: false
        type: string
      GHCR_IMAGE_NAME:
        default: react
        required: false
        type: string
      GHCR_REPOSITORY_NAME:
        default: qatranslator
        required: false
        type: string
      RESOURCE_GROUP:
        default: qatranslator-je
        required: false
        type: string
    secrets:
      AZURE_AD_SP_CONTRIBUTOR_CLIENT_ID:
        required: true
      AZURE_AD_SP_CONTRIBUTOR_CLIENT_SECRET:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true
      AZURE_TENANT_ID:
        required: true

jobs:
  build-ghcr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Login Azure as Contributor
        uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.AZURE_AD_SP_CONTRIBUTOR_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_AD_SP_CONTRIBUTOR_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'
          enable-AzPSSession: true

      - name: Get API Management Subscription Key
        id: get_api_management_subscription_key
        uses: azure/powershell@v1
        with:
          inlineScript: |
            $apimContext = New-AzApiManagementContext `
              -ResourceGroupName "${{ inputs.RESOURCE_GROUP }}" `
              -ServiceName "${{ inputs.APIM_NAME }}"
            $apimFunctionsSubscriptionKey = Get-AzApiManagementSubscriptionKey `
              -Context $apimContext `
              -SubscriptionId "${{ inputs.APIM_SUBSCRIPTION_NAME }}"
            $apimSubscriptionKey = $apimFunctionsSubscriptionKey.PrimaryKey
            Write-Output "::add-mask::${apimSubscriptionKey}"
            Write-Output "apim_subscription_key=${apimSubscriptionKey}" >> $env:GITHUB_OUTPUT
          azPSVersion: latest

      - name: Get Cognitive Service Account Key
        id: get_cognitive_key
        run: |
          cognitiveKey=$( \
            az cognitiveservices account keys list \
              -g ${{ inputs.RESOURCE_GROUP }} \
              -n ${{ inputs.COGNITIVE_NAME }} \
              --query "key1" \
              -o tsv \
          )
          echo "cognitive_key=${cognitiveKey}" >> $GITHUB_OUTPUT

      - name: Replace Secure Environment Variables
        run: |
          sed -i \
            -e 's/VALUE_OF_REACT_APP_API_MANAGEMENT_SUBSCRIPTION_KEY/${{ steps.get_api_management_subscription_key.outputs.apim_subscription_key }}/g' \
            -e 's/VALUE_OF_REACT_APP_AZURE_AD_SP_MSAL_CLIENT_ID/${{ secrets.AZURE_AD_SP_MSAL_CLIENT_ID }}/g' \
            -e 's/VALUE_OF_REACT_APP_AZURE_COGNITIVE_KEY/${{ steps.get_cognitive_key.outputs.cognitive_key }}/g' \
            -e 's/VALUE_OF_REACT_APP_AZURE_TENANT_ID/${{ secrets.AZURE_TENANT_ID }}/g' \
            -e 's/VALUE_OF_REACT_APP_DEEPL_AUTH_KEY/${{ secrets.DEEPL_AUTH_KEY }}/g' \
            react/.env.production

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Build and Docker Push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: react/Dockerfile
          push: true
          tags: ghcr.io/${{ github.actor }}/${{ inputs.GHCR_REPOSITORY_NAME }}/${{ inputs.GHCR_IMAGE_NAME }}:${{ github.sha	}}
