name: Deploy API Management (Reusable Workflow)

on:
  workflow_call:
    inputs:
      APIM_APIS_NAME:
        required: true
        type: string
      APIM_NAME:
        required: true
        type: string
      RESOURCE_GROUP:
        required: true
        type: string
    secrets:
      AZURE_AD_SP_CONTRIBUTOR_CLIENT_ID:
        required: true
      AZURE_AD_SP_CONTRIBUTOR_CLIENT_SECRET:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true
      AZURE_TENANT_ID:
        required: true

jobs:
  deploy-apim:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Login Azure as Contributor
        uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.AZURE_AD_SP_CONTRIBUTOR_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_AD_SP_CONTRIBUTOR_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'

      - name: Import Swagger into API Management
        run: |
          az apim api import \
            -g ${{ inputs.RESOURCE_GROUP }} \
            -n ${{ inputs.APIM_NAME }} \
            --path "api" \
            --specification-format OpenApi \
            --api-id ${{ inputs.APIM_APIS_NAME }} \
            --specification-path ./apim/swagger.yaml
